module.exports = {
    moduleFileExtensions: ['js'],
    transform: {
        '^.+\\.js$': './jest-transform.js',
    },
    transformIgnorePatterns: [
        // transform ES6 modules generated by BuckleScript
        // https://regexr.com/46984
        '/node_modules/(?!(@.*/)?(bs-.*|reason-.*|rescript.*|@rescript.*)/).+\\.js$',
    ],
    testEnvironment: "jsdom",
    moduleNameMapper: {
        "@fontsource/*": "<rootDir>/__mocks__/font-mock.js",
        "\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$": "<rootDir>/__mocks__/fileMock.js",
        // other rules...
    },
};